name: authmed2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24
  - matplotlib=3.7
  - pandas
  - pytorch
  - torchvision
  - pip
  - pip:
    - inference_sdk
    - supervision
